[package]
name = "rust-xcompile"
version = "0.1.0"
authors = ["Kamil Samaj <kamil.samaj@accolade.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
